from __future__ import annotations

import re

from named_values_common import insert_before, read, regex_once, replace_once

VM = "01-lang/010-bytecode/draft/hal-bytecode-vm.edn"
CASES = "01-lang/010-bytecode/draft/conformance/bytecode-vm.edn"
README = "01-lang/010-bytecode/draft/README.md"

replace_once(
    VM,
    ":private-artifacts #{:HBC1 :HBC2 :HBC3 :HBC4 :HNW0 :Program :Instruction :whole-function-mir :numeric-slots :handler-table :call-frames}",
    ":private-artifacts #{:HBC0 :HNW0 :Program :Instruction :whole-function-mir :numeric-slots :handler-table :call-frames}",
)
replace_once(
    VM,
    "HBC4 persists both with the executable program; HBC1-HBC3 remain readable legacy inputs with empty type tables.",
    "HBC0 persists both with the executable program. Opcode numbers are append-only; retired encodings fail closed with a rebuild-required diagnostic.",
)
regex_once(
    VM,
    r"   \{:op StructField :operand :u32-constant-index :pops 1 :pushes 1\n    :meaning \"pop a struct instance, push the positional field value named by the keyword constant \(the field special form\)\"\}",
    '''   {:op DefMutable :operand {:name :u32-constant-index :fields :u32-constant-index}
    :pops 0 :pushes 1
    :meaning "create a mutable named type qualified to the current namespace, intern Name, ->Name, and map->Name constructor Vars, and push nil; fields is a vector constant of field-name strings"}
   {:op MutableFieldGet :operand :u32-constant-index :pops 1 :pushes 1
    :meaning "pop a defmutable instance and push the declared field value named by the string constant"}
   {:op MutableFieldSet :operand :u32-constant-index :pops 2 :pushes 1
    :meaning "pop replacement and receiver, mutate one declared field, and push the replacement value"}''',
)
replace_once(
    VM,
    '"pop the value then the struct type; push whether the value is an instance (the instance? special form)"',
    '"pop the value then a defstruct or defmutable type descriptor; push whether the value is an instance (the instance? special form)"',
)
insert_before(
    VM,
    " :vm/program\n",
    ''' :vm/persistent-opcodes
 {:format :HBC0
  :numbering :append-only
  :named-values
  [{:opcode 20 :op DefStruct :status :active}
   {:opcode 21
    :op StructField
    :status :retired
    :decode-error "bytecode artifact uses retired StructField opcode 21; rebuild required"}
   {:opcode 47 :op DefMutable :status :active}
   {:opcode 48 :op MutableFieldGet :status :active}
   {:opcode 49 :op MutableFieldSet :status :active}]
  :compatibility-rule
  "An assigned opcode number is never renumbered or reused. Decoding retired opcode 21 fails with the exact rebuild-required diagnostic; incompatible future program envelopes use a new magic rather than guessing."
  :source-of-truth "core/rust/src/vm/artifact.rs"}

''',
)
replace_once(VM, ":format :HBC4", ":format :HBC0")
replace_once(
    VM,
    '"four-byte HBC4 magic followed by a big-endian u32 payload length"',
    '"four-byte HBC0 magic followed by a big-endian u32 payload length"',
)
replace_once(
    VM,
    '"the version is carried by the magic; HBC1-HBC3 decode with empty schema tables, and incompatible future encodings use a new magic rather than guessing"',
    '"HBC0 is the only accepted program magic. Opcode numbers are append-only within HBC0; retired opcode 21 reports rebuild required; incompatible future envelopes use a new magic rather than guessing"',
)
replace_once(
    VM,
    "   :defstruct-fields-constant-not-a-string-vector\n",
    "   :defstruct-fields-constant-not-a-string-vector\n   :defmutable-fields-constant-not-a-string-vector\n   :mutable-field-name-constant-not-a-string\n",
)
replace_once(
    VM,
    "top-level declare, def, defn, defstruct in the same source",
    "top-level declare, def, defn, defstruct, defmutable, and the Name/->Name/map->Name constructors generated by either named-value definition in the same source",
)

insert_before(
    CASES,
    "  ;; ---- exceptions: try/catch/finally and guest throw ----\n",
    '''  ;; ---- persistent and mutable named values ----
  {:id :named-value/defstruct-constructors
   :source "(do (defstruct Point [x y]) (+ (get (Point 1 2) :x) (get (->Point 3 4) :x) (get (map->Point {:x 5}) :x)))"
   :expect {:display "9"}}
  {:id :named-value/defmutable-constructors
   :source "(do (defmutable Cursor [x y]) (+ (field (Cursor 1 2) :x) (field (->Cursor 3 4) :x) (field (map->Cursor {:x 5}) :x)))"
   :expect {:display "9"}}
  {:id :named-value/mutable-alias-set-result
   :source "(do (defmutable Cursor [x y]) (let [cursor (Cursor 1 2) alias cursor result (set! (field cursor :x) 42)] (+ result (field alias :x))))"
   :expect {:display "84"}}
  {:id :named-value/mutable-identity
   :source "(do (defmutable Cursor [x y]) (let [cursor (Cursor 1 2) alias cursor] (if (= cursor alias) (if (= cursor (Cursor 1 2)) 0 42) 0)))"
   :expect {:display "42"}}
  {:id :named-value/mutable-evaluation-order
   :source "(do (defmutable Cursor [x]) (def named-value-order 0) (let [cursor (Cursor 1)] (set! (field (do (set! named-value-order (+ (* named-value-order 10) 1)) cursor) :x) (do (set! named-value-order (+ (* named-value-order 10) 2)) 42)) named-value-order))"
   :expect {:display "12"}}

''',
)

insert_before(
    README,
    "- namespace-owned callable Vars, protected referrals, and `declare` as\n",
    "- persistent `defstruct` and reference-identity `defmutable` definitions,\n  same-unit constructor visibility, and dedicated mutable field read/write\n  instructions;\n- append-only HBC0 opcode compatibility, including the retired opcode 21\n  rebuild-required diagnostic;\n",
)
replace_once(
    README,
    "`:compile-error` cases pin VM-only lowering boundaries. Namespace, reload, and",
    "`:compile-error` cases pin VM-only lowering boundaries. The corpus also pins\n`defstruct`/`defmutable` constructor visibility, mutable identity, alias-visible\nwrites, return values, and field-place evaluation order. Namespace, reload, and",
)

vm = read(VM)
if ":format :HBC4" in vm or "HBC1-HBC3 remain readable" in vm:
    raise SystemExit(f"{VM}: stale HBC version text remains")
if vm.count("bytecode artifact uses retired StructField opcode 21; rebuild required") != 1:
    raise SystemExit(f"{VM}: retired opcode diagnostic must occur exactly once")

print("Updated the HBC0 named-value instruction and conformance contract.")
